name: Publish image

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**
  workflow_dispatch:

jobs:
  publish:
    name: Build Docker image and push
    uses: nelfimov/workflows/.github/workflows/publish-image.yaml@master
    permissions:
      packages: write
      contents: read
      id-token: write
    with:
      imageName: microarch-delivery
